-- SQL JOINS

-- 1. List the number of films per category.

use sakila;

SELECT name, count(title) as number_of_films
FROM film_category
JOIN category
ON film_category.category_id = category.category_id
JOIN film
ON film_category.film_id = film.film_id
group by name
;

-- 2. Retrieve the store ID, city, and country for each store.

select store_id as store, city, country
from address
join store
on address.address_id = store.address_id
join city
on address.city_id = city.city_id
join country
on city.country_id = country.country_id
;

-- 3. Calculate the total revenue generated by each store in dollars.

select customer.store_id, customer_id
from customer
join store
on customer.store_id = store.store_id
;

-- 4. Determine the average running time of films for each category.

/*
Bonus:

    Identify the film categories with the longest average running time.
    Display the top 10 most frequently rented movies in descending order.
    Determine if "Academy Dinosaur" can be rented from Store 1.
    Provide a list of all distinct film titles, along with their availability status in the inventory.
    Include a column indicating whether each title is 'Available' or 'NOT available.'
    Note that there are 42 titles that are not in the inventory, and this information can be obtained 
    using a CASE statement combined with IFNULL."

*/